name: task_management_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  english_words: ^4.0.0
  provider: ^6.0.0
  parse_server_sdk_flutter: ^9.0.0
  flutter_dotenv: ^5.0.2 # Add the dotenv package here

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
